// ---Auto Generated by Only4Play ---
package com.only4play.system.controller;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.model.JsonObject;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.common.model.PageResult;
import com.only4play.system.domain.trade.orderitem.creator.OrderItemCreator;
import com.only4play.system.domain.trade.orderitem.mapper.OrderItemMapper;
import com.only4play.system.domain.trade.orderitem.query.OrderItemQuery;
import com.only4play.system.domain.trade.orderitem.request.OrderItemCreateRequest;
import com.only4play.system.domain.trade.orderitem.request.OrderItemQueryRequest;
import com.only4play.system.domain.trade.orderitem.request.OrderItemUpdateRequest;
import com.only4play.system.domain.trade.orderitem.response.OrderItemResponse;
import com.only4play.system.domain.trade.orderitem.service.IOrderItemService;
import com.only4play.system.domain.trade.orderitem.updater.OrderItemUpdater;
import com.only4play.system.domain.trade.orderitem.vo.OrderItemVO;
import java.lang.Long;
import java.lang.String;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("orderItem/v1")
@RequiredArgsConstructor
public class OrderItemController {
  private final IOrderItemService orderItemService;

  /**
   * createRequest
   */
  @PostMapping("createOrderItem")
  public JsonObject<Long> createOrderItem(@RequestBody OrderItemCreateRequest request) {
    OrderItemCreator creator = OrderItemMapper.INSTANCE.request2Dto(request);
    return JsonObject.success(orderItemService.createOrderItem(creator));
  }

  /**
   * update request
   */
  @PostMapping("updateOrderItem")
  public JsonObject<String> updateOrderItem(@RequestBody OrderItemUpdateRequest request) {
    OrderItemUpdater updater = OrderItemMapper.INSTANCE.request2Updater(request);
    orderItemService.updateOrderItem(updater);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * valid
   */
  @PostMapping("valid/{id}")
  public JsonObject<String> validOrderItem(@PathVariable Long id) {
    orderItemService.validOrderItem(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * invalid
   */
  @PostMapping("invalid/{id}")
  public JsonObject<String> invalidOrderItem(@PathVariable Long id) {
    orderItemService.invalidOrderItem(id);
    return JsonObject.success(CodeEnum.Success.getName());
  }

  /**
   * findById
   */
  @GetMapping("findById/{id}")
  public JsonObject<OrderItemResponse> findById(@PathVariable Long id) {
    OrderItemVO vo = orderItemService.findById(id);
    OrderItemResponse response = OrderItemMapper.INSTANCE.vo2CustomResponse(vo);
    return JsonObject.success(response);
  }

  /**
   * findByPage request
   */
  @PostMapping("findByPage")
  public JsonObject<PageResult<OrderItemResponse>> findByPage(
      @RequestBody PageRequestWrapper<OrderItemQueryRequest> request) {
    PageRequestWrapper<OrderItemQuery> wrapper = new PageRequestWrapper<>();
    wrapper.setBean(OrderItemMapper.INSTANCE.request2Query(request.getBean()));
    wrapper.setSorts(request.getSorts());
        wrapper.setPageSize(request.getPageSize());
        wrapper.setPage(request.getPage());
    Page<OrderItemVO> page = orderItemService.findByPage(wrapper);
    return JsonObject.success(
            PageResult.of(
                page.getContent().stream()
                    .map(vo -> OrderItemMapper.INSTANCE.vo2CustomResponse(vo))
                    .collect(Collectors.toList()),
                page.getTotalElements(),
                page.getSize(),
                page.getNumber())
        );
  }
}
